-- hds header_start
--
-- VHDL Architecture ECE290_GATES.ANDgate.untitled
--
-- Created:
--          by - mrmcclai.stdt (glsn22.ews.uiuc.edu)
--          at - 18:07:51 06/22/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;


ENTITY ANDgate5 IS
   PORT( 
      v : IN     std_logic;
      w : IN     std_logic;
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );

-- Declarations

END ANDgate5 ;

-- hds interface_end
ARCHITECTURE untitled OF ANDgate5 IS
BEGIN
  F <= V and W and X and Y and Z after 1 ns;
END untitled;
