-- VHDL Entity LAB3.CLA64bit.symbol
--
-- Created:
--          by - kim705.ews (dcl-l520-04.ews.illinois.edu)
--          at - 20:16:46 09/19/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY CLA64bit IS
   PORT( 
      A    : IN     std_logic_vector (63 DOWNTO 0);
      B    : IN     std_logic_vector (63 DOWNTO 0);
      Cin  : IN     std_logic;
      Cout : OUT    std_logic;
      Gg   : OUT    std_logic;
      Pg   : OUT    std_logic;
      S    : OUT    std_logic_vector (63 DOWNTO 0)
   );

-- Declarations

END CLA64bit ;

--
-- VHDL Architecture LAB3.CLA64bit.struct
--
-- Created:
--          by - kim705.ews (dcl-l520-04.ews.illinois.edu)
--          at - 20:16:46 09/19/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY LAB3;

ARCHITECTURE struct OF CLA64bit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL C1  : std_logic;
   SIGNAL C2  : std_logic;
   SIGNAL C3  : std_logic;
   SIGNAL G1  : std_logic;
   SIGNAL G2  : std_logic;
   SIGNAL G3  : std_logic;
   SIGNAL Gg1 : std_logic;
   SIGNAL P0  : std_logic;
   SIGNAL P1  : std_logic;
   SIGNAL P2  : std_logic;
   SIGNAL P3  : std_logic;


   -- Component Declarations
   COMPONENT CLA16bit
   PORT (
      A    : IN     std_logic_vector (15 DOWNTO 0);
      B    : IN     std_logic_vector (15 DOWNTO 0);
      Cin  : IN     std_logic ;
      Cout : OUT    std_logic ;
      Gg   : OUT    std_logic ;
      Pg   : OUT    std_logic ;
      S    : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT CLAlogic
   PORT (
      C0 : IN     std_logic ;
      G0 : IN     std_logic ;
      G1 : IN     std_logic ;
      G2 : IN     std_logic ;
      G3 : IN     std_logic ;
      P0 : IN     std_logic ;
      P1 : IN     std_logic ;
      P2 : IN     std_logic ;
      P3 : IN     std_logic ;
      C1 : OUT    std_logic ;
      C2 : OUT    std_logic ;
      C3 : OUT    std_logic ;
      C4 : OUT    std_logic ;
      Gg : OUT    std_logic ;
      Pg : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CLA16bit USE ENTITY LAB3.CLA16bit;
   FOR ALL : CLAlogic USE ENTITY LAB3.CLAlogic;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : CLA16bit
      PORT MAP (
         A    => A(63 DOWNTO 48),
         B    => B(63 DOWNTO 48),
         Cin  => C3,
         Cout => OPEN,
         Gg   => G3,
         Pg   => P3,
         S    => S(63 DOWNTO 48)
      );
   I1 : CLA16bit
      PORT MAP (
         A    => A(47 DOWNTO 32),
         B    => B(47 DOWNTO 32),
         Cin  => C2,
         Cout => OPEN,
         Gg   => G2,
         Pg   => P2,
         S    => S(47 DOWNTO 32)
      );
   I2 : CLA16bit
      PORT MAP (
         A    => A(31 DOWNTO 16),
         B    => B(31 DOWNTO 16),
         Cin  => C1,
         Cout => OPEN,
         Gg   => G1,
         Pg   => P1,
         S    => S(31 DOWNTO 16)
      );
   I3 : CLA16bit
      PORT MAP (
         A    => A(15 DOWNTO 0),
         B    => B(15 DOWNTO 0),
         Cin  => Cin,
         Cout => OPEN,
         Gg   => Gg1,
         Pg   => P0,
         S    => S(15 DOWNTO 0)
      );
   I4 : CLAlogic
      PORT MAP (
         C0 => Cin,
         G0 => Gg1,
         G1 => G1,
         G2 => G2,
         G3 => G3,
         P0 => P0,
         P1 => P1,
         P2 => P2,
         P3 => P3,
         C1 => C1,
         C2 => C2,
         C3 => C3,
         C4 => Cout,
         Gg => Gg,
         Pg => Pg
      );

END struct;
