-- VHDL Entity LAB3.CLAlogic.symbol
--
-- Created:
--          by - kim705.ews (gelib-057-35.ews.illinois.edu)
--          at - 21:41:08 09/18/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY CLAlogic IS
   PORT( 
      C0 : IN     std_logic;
      G0 : IN     std_logic;
      G1 : IN     std_logic;
      G2 : IN     std_logic;
      G3 : IN     std_logic;
      P0 : IN     std_logic;
      P1 : IN     std_logic;
      P2 : IN     std_logic;
      P3 : IN     std_logic;
      C1 : OUT    std_logic;
      C2 : OUT    std_logic;
      C3 : OUT    std_logic;
      C4 : OUT    std_logic;
      Gg : OUT    std_logic;
      Pg : OUT    std_logic
   );

-- Declarations

END CLAlogic ;

--
-- VHDL Architecture LAB3.CLAlogic.struct
--
-- Created:
--          by - kim705.ews (gelib-057-35.ews.illinois.edu)
--          at - 21:41:08 09/18/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.ALL;

LIBRARY LAB3;

ARCHITECTURE struct OF CLAlogic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F2     : std_logic;
   SIGNAL din0   : std_logic;
   SIGNAL din1   : std_logic;
   SIGNAL din25  : std_logic;
   SIGNAL din25a : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout4a : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout5a : std_logic;
   SIGNAL dout7a : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL f      : std_logic;
   SIGNAL f1     : std_logic;


   -- Component Declarations
   COMPONENT ANDgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ANDgate3
   PORT (
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ANDgate4
   PORT (
      w : IN     std_logic;
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ANDgate5
   PORT (
      v : IN     std_logic;
      w : IN     std_logic;
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ORgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ORgate3
   PORT (
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ORgate4
   PORT (
      w : IN     std_logic;
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ORgate5
   PORT (
      v : IN     std_logic;
      w : IN     std_logic;
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ANDgate USE ENTITY LAB3.ANDgate;
   FOR ALL : ANDgate3 USE ENTITY LAB3.ANDgate3;
   FOR ALL : ANDgate4 USE ENTITY LAB3.ANDgate4;
   FOR ALL : ANDgate5 USE ENTITY LAB3.ANDgate5;
   FOR ALL : ORgate USE ENTITY LAB3.ORgate;
   FOR ALL : ORgate3 USE ENTITY LAB3.ORgate3;
   FOR ALL : ORgate4 USE ENTITY LAB3.ORgate4;
   FOR ALL : ORgate5 USE ENTITY LAB3.ORgate5;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I3 : ANDgate
      PORT MAP (
         X => P0,
         Y => C0,
         F => din0
      );
   I6 : ANDgate
      PORT MAP (
         X => P1,
         Y => G0,
         F => dout8
      );
   I8 : ANDgate
      PORT MAP (
         X => P2,
         Y => G1,
         F => F2
      );
   I9 : ANDgate
      PORT MAP (
         X => P3,
         Y => G2,
         F => dout5a
      );
   I10 : ANDgate
      PORT MAP (
         X => P3,
         Y => G2,
         F => dout5
      );
   I4 : ANDgate3
      PORT MAP (
         x => P0,
         y => P1,
         z => C0,
         f => din1
      );
   I11 : ANDgate3
      PORT MAP (
         x => P1,
         y => P2,
         z => G0,
         f => f
      );
   I12 : ANDgate3
      PORT MAP (
         x => P2,
         y => P3,
         z => G1,
         f => dout4a
      );
   I13 : ANDgate3
      PORT MAP (
         x => P2,
         y => P3,
         z => G1,
         f => dout4
      );
   I1 : ANDgate4
      PORT MAP (
         w => P3,
         x => P1,
         y => P2,
         z => P0,
         f => Pg
      );
   I14 : ANDgate4
      PORT MAP (
         w => P3,
         x => P1,
         y => P2,
         z => G0,
         f => din25
      );
   I15 : ANDgate4
      PORT MAP (
         w => P3,
         x => P1,
         y => P2,
         z => G0,
         f => din25a
      );
   I19 : ANDgate4
      PORT MAP (
         w => P2,
         x => P0,
         y => P1,
         z => C0,
         f => f1
      );
   I16 : ANDgate5
      PORT MAP (
         v => P3,
         w => P2,
         x => P0,
         y => P1,
         z => C0,
         f => dout7a
      );
   I7 : ORgate
      PORT MAP (
         X => din0,
         Y => G0,
         F => C1
      );
   I17 : ORgate3
      PORT MAP (
         x => dout8,
         y => din1,
         z => G1,
         f => C2
      );
   I2 : ORgate4
      PORT MAP (
         w => din25,
         x => dout5,
         y => dout4,
         z => G3,
         f => Gg
      );
   I5 : ORgate4
      PORT MAP (
         w => f1,
         x => F2,
         y => f,
         z => G2,
         f => C3
      );
   I18 : ORgate5
      PORT MAP (
         v => din25a,
         w => dout7a,
         x => dout5a,
         y => dout4a,
         z => G3,
         f => C4
      );

END struct;
