-- VHDL Entity LAB3.FA.symbol
--
-- Created:
--          by - kim705.ews (gelib-057-35.ews.illinois.edu)
--          at - 19:55:05 09/18/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FA IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      cin  : IN     std_logic;
      cout : OUT    std_logic;
      s    : OUT    std_logic
   );

-- Declarations

END FA ;

--
-- VHDL Architecture LAB3.FA.struct
--
-- Created:
--          by - kim705.ews (gelib-057-35.ews.illinois.edu)
--          at - 19:55:05 09/18/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;

LIBRARY LAB3;

ARCHITECTURE struct OF FA IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F  : std_logic;
   SIGNAL X2 : std_logic;
   SIGNAL X3 : std_logic;


   -- Component Declarations
   COMPONENT ANDgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ORgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT XORgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ANDgate USE ENTITY LAB3.ANDgate;
   FOR ALL : ORgate USE ENTITY LAB3.ORgate;
   FOR ALL : XORgate USE ENTITY LAB3.XORgate;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : ANDgate
      PORT MAP (
         X => X3,
         Y => cin,
         F => X2
      );
   U_4 : ANDgate
      PORT MAP (
         X => a,
         Y => b,
         F => F
      );
   U_2 : ORgate
      PORT MAP (
         X => X2,
         Y => F,
         F => cout
      );
   U_0 : XORgate
      PORT MAP (
         X => cin,
         Y => X3,
         F => s
      );
   U_3 : XORgate
      PORT MAP (
         X => b,
         Y => a,
         F => X3
      );

END struct;
