-- VHDL Entity project1_lib.channel_selection.symbol
--
-- Created:
--          by - kim705.ews (evrt-252-23.ews.illinois.edu)
--          at - 23:05:26 10/01/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY channel_selection IS
   PORT( 
      S      : IN     std_logic_vector (1 DOWNTO 0);
      ch1    : IN     std_logic_vector (19 DOWNTO 0);
      ch2    : IN     std_logic_vector (19 DOWNTO 0);
      ch3    : IN     std_logic_vector (19 DOWNTO 0);
      ch4    : IN     std_logic_vector (19 DOWNTO 0);
      ch_out : OUT    std_logic_vector (19 DOWNTO 0)
   );

-- Declarations

END channel_selection ;

--
-- VHDL Architecture project1_lib.channel_selection.struct
--
-- Created:
--          by - kim705.ews (evrt-252-23.ews.illinois.edu)
--          at - 23:05:26 10/01/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF channel_selection IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.7) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(ch1, ch2, ch3, ch4, S)
   BEGIN
      CASE S IS
      WHEN "00"|"L0"|"0L"|"LL" => ch_out <= ch1;
      WHEN "01"|"L1"|"0H"|"LH" => ch_out <= ch2;
      WHEN "10"|"H0"|"1L"|"HL" => ch_out <= ch3;
      WHEN "11"|"H1"|"1H"|"HH" => ch_out <= ch4;
      WHEN OTHERS => ch_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- Instance port mappings.

END struct;
