-- VHDL Entity LAB3.CLA16bit.symbol
--
-- Created:
--          by - tkim26.ews (gelib-057-21.ews.illinois.edu)
--          at - 09:46:01 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY CLA16bit IS
   PORT( 
      A    : IN     std_logic_vector (15 DOWNTO 0);
      B    : IN     std_logic_vector (15 DOWNTO 0);
      Cin  : IN     std_logic;
      Cout : OUT    std_logic;
      Gg   : OUT    std_logic;
      Pg   : OUT    std_logic;
      S    : OUT    std_logic_vector (15 DOWNTO 0)
   );

-- Declarations

END CLA16bit ;

--
-- VHDL Architecture LAB3.CLA16bit.struct
--
-- Created:
--          by - tkim26.ews (gelib-057-21.ews.illinois.edu)
--          at - 09:46:02 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY LAB3;

ARCHITECTURE struct OF CLA16bit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL C1 : std_logic;
   SIGNAL C2 : std_logic;
   SIGNAL C3 : std_logic;
   SIGNAL G0 : std_logic;
   SIGNAL G1 : std_logic;
   SIGNAL G2 : std_logic;
   SIGNAL G3 : std_logic;
   SIGNAL P0 : std_logic;
   SIGNAL P1 : std_logic;
   SIGNAL P2 : std_logic;
   SIGNAL P3 : std_logic;


   -- Component Declarations
   COMPONENT CLA4bit
   PORT (
      Cin  : IN     std_logic ;
      a0   : IN     std_logic ;
      a1   : IN     std_logic ;
      a2   : IN     std_logic ;
      a3   : IN     std_logic ;
      b0   : IN     std_logic ;
      b1   : IN     std_logic ;
      b2   : IN     std_logic ;
      b3   : IN     std_logic ;
      Cout : OUT    std_logic ;
      Gg   : OUT    std_logic ;
      Pg   : OUT    std_logic ;
      s0   : OUT    std_logic ;
      s1   : OUT    std_logic ;
      s2   : OUT    std_logic ;
      s3   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT CLAlogic
   PORT (
      C0 : IN     std_logic ;
      G0 : IN     std_logic ;
      G1 : IN     std_logic ;
      G2 : IN     std_logic ;
      G3 : IN     std_logic ;
      P0 : IN     std_logic ;
      P1 : IN     std_logic ;
      P2 : IN     std_logic ;
      P3 : IN     std_logic ;
      C1 : OUT    std_logic ;
      C2 : OUT    std_logic ;
      C3 : OUT    std_logic ;
      C4 : OUT    std_logic ;
      Gg : OUT    std_logic ;
      Pg : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CLA4bit USE ENTITY LAB3.CLA4bit;
   FOR ALL : CLAlogic USE ENTITY LAB3.CLAlogic;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : CLA4bit
      PORT MAP (
         Cin  => C3,
         a0   => A(12),
         a1   => A(13),
         a2   => A(14),
         a3   => A(15),
         b0   => B(12),
         b1   => B(13),
         b2   => B(14),
         b3   => B(15),
         Cout => OPEN,
         Gg   => G3,
         Pg   => P3,
         s0   => S(12),
         s1   => S(13),
         s2   => S(14),
         s3   => S(15)
      );
   I1 : CLA4bit
      PORT MAP (
         Cin  => C2,
         a0   => A(8),
         a1   => A(9),
         a2   => A(10),
         a3   => A(11),
         b0   => B(8),
         b1   => B(9),
         b2   => B(10),
         b3   => B(11),
         Cout => OPEN,
         Gg   => G2,
         Pg   => P2,
         s0   => S(8),
         s1   => S(9),
         s2   => S(10),
         s3   => S(11)
      );
   I2 : CLA4bit
      PORT MAP (
         Cin  => C1,
         a0   => A(4),
         a1   => A(5),
         a2   => A(6),
         a3   => A(7),
         b0   => B(4),
         b1   => B(5),
         b2   => B(6),
         b3   => B(7),
         Cout => OPEN,
         Gg   => G1,
         Pg   => P1,
         s0   => S(4),
         s1   => S(5),
         s2   => S(6),
         s3   => S(7)
      );
   I3 : CLA4bit
      PORT MAP (
         Cin  => Cin,
         a0   => A(0),
         a1   => A(1),
         a2   => A(2),
         a3   => A(3),
         b0   => B(0),
         b1   => B(1),
         b2   => B(2),
         b3   => B(3),
         Cout => OPEN,
         Gg   => G0,
         Pg   => P0,
         s0   => S(0),
         s1   => S(1),
         s2   => S(2),
         s3   => S(3)
      );
   I4 : CLAlogic
      PORT MAP (
         C0 => Cin,
         G0 => G0,
         G1 => G1,
         G2 => G2,
         G3 => G3,
         P0 => P0,
         P1 => P1,
         P2 => P2,
         P3 => P3,
         C1 => C1,
         C2 => C2,
         C3 => C3,
         C4 => Cout,
         Gg => Gg,
         Pg => Pg
      );

END struct;
