-- VHDL Entity project1_lib.descrambler.symbol
--
-- Created:
--          by - kim705.ews (evrt-252-23.ews.illinois.edu)
--          at - 23:15:59 10/01/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY descrambler IS
   PORT( 
      d0  : IN     std_logic;
      d1  : IN     std_logic;
      d2  : IN     std_logic;
      d3  : IN     std_logic;
      d_0 : OUT    std_logic;
      d_1 : OUT    std_logic;
      d_2 : OUT    std_logic;
      d_3 : OUT    std_logic
   );

-- Declarations

END descrambler ;

--
-- VHDL Architecture project1_lib.descrambler.struct
--
-- Created:
--          by - kim705.ews (evrt-252-23.ews.illinois.edu)
--          at - 23:15:59 10/01/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF descrambler IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;



BEGIN

   -- ModuleWare code(v1.7) for instance 'U_3' of 'and'
   dout <= d2 AND d3;

   -- ModuleWare code(v1.7) for instance 'U_5' of 'and'
   dout3 <= d0 AND d1;

   -- ModuleWare code(v1.7) for instance 'U_6' of 'and'
   dout4 <= d0 AND d2 AND d3;

   -- ModuleWare code(v1.7) for instance 'U_7' of 'and'
   dout5 <= d2 AND d3;

   -- ModuleWare code(v1.7) for instance 'U_0' of 'inv'
   d_0 <= NOT(d3);

   -- ModuleWare code(v1.7) for instance 'U_2' of 'nor'
   d_2 <= NOT(dout OR d2);

   -- ModuleWare code(v1.7) for instance 'U_4' of 'nor'
   dout6 <= NOT(dout5 OR d0 OR d1);

   -- ModuleWare code(v1.7) for instance 'U_12' of 'or'
   d_3 <= dout3 OR dout4 OR dout6;

   -- ModuleWare code(v1.7) for instance 'U_1' of 'xor'
   d_1 <= d2 XOR d3;

   -- Instance port mappings.

END struct;
