-- VHDL Entity ece290_project1_lib.encryption_5bit.symbol
--
-- Created:
--          by - akim77.ews (evrt-252-37.ews.illinois.edu)
--          at - 20:59:45 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY encryption_5bit IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      c    : IN     std_logic;
      d    : IN     std_logic;
      x0   : IN     std_logic;
      x1   : IN     std_logic;
      x2   : IN     std_logic;
      x3   : IN     std_logic;
      x4   : IN     std_logic;
      x0a  : OUT    std_logic;
      x0a1 : OUT    std_logic;
      x0a2 : OUT    std_logic;
      x0a3 : OUT    std_logic;
      x0a4 : OUT    std_logic;
      x0b  : OUT    std_logic;
      x0b1 : OUT    std_logic;
      x0b2 : OUT    std_logic;
      x0b3 : OUT    std_logic;
      x0b4 : OUT    std_logic;
      x0c  : OUT    std_logic;
      x0c1 : OUT    std_logic;
      x0c2 : OUT    std_logic;
      x0c3 : OUT    std_logic;
      x0c4 : OUT    std_logic;
      x0d  : OUT    std_logic;
      x0d1 : OUT    std_logic;
      x0d2 : OUT    std_logic;
      x0d3 : OUT    std_logic;
      x0d4 : OUT    std_logic
   );

-- Declarations

END encryption_5bit ;

--
-- VHDL Architecture ece290_project1_lib.encryption_5bit.struct
--
-- Created:
--          by - akim77.ews (evrt-252-37.ews.illinois.edu)
--          at - 20:59:45 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece290_project1_lib;

ARCHITECTURE struct OF encryption_5bit IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT encryption
   PORT (
      a   : IN     std_logic ;
      b   : IN     std_logic ;
      c   : IN     std_logic ;
      d   : IN     std_logic ;
      x0  : IN     std_logic ;
      x0a : OUT    std_logic ;
      x0b : OUT    std_logic ;
      x0c : OUT    std_logic ;
      x0d : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : encryption USE ENTITY ece290_project1_lib.encryption;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x3,
         x0a => x0a3,
         x0b => x0b3,
         x0c => x0c3,
         x0d => x0d3
      );
   U_1 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x0,
         x0a => x0a,
         x0b => x0b,
         x0c => x0c,
         x0d => x0d
      );
   U_2 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x1,
         x0a => x0a1,
         x0b => x0b1,
         x0c => x0c1,
         x0d => x0d1
      );
   U_3 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x4,
         x0a => x0a4,
         x0b => x0b4,
         x0c => x0c4,
         x0d => x0d4
      );
   U_4 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x2,
         x0a => x0a2,
         x0b => x0b2,
         x0c => x0c2,
         x0d => x0d2
      );

END struct;
