-- VHDL Entity LAB3.FA.symbol
--
-- Created:
--          by - tkim26.ews (gelib-057-12.ews.illinois.edu)
--          at - 21:16:09 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FA IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      cin  : IN     std_logic;
      cout : OUT    std_logic;
      s    : OUT    std_logic
   );

-- Declarations

END FA ;

--
-- VHDL Architecture LAB3.FA.struct
--
-- Created:
--          by - tkim26.ews (gelib-057-12.ews.illinois.edu)
--          at - 21:16:09 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;

LIBRARY LAB3;

ARCHITECTURE struct OF FA IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F    : std_logic;
   SIGNAL Y1   : std_logic;
   SIGNAL dout : std_logic;


   -- Component Declarations
   COMPONENT ANDgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT ORgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT XORgate
   PORT (
      X : IN     std_logic;
      Y : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ANDgate USE ENTITY LAB3.ANDgate;
   FOR ALL : ORgate USE ENTITY LAB3.ORgate;
   FOR ALL : XORgate USE ENTITY LAB3.XORgate;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : ANDgate
      PORT MAP (
         X => a,
         Y => b,
         F => dout
      );
   U_1 : ANDgate
      PORT MAP (
         X => Y1,
         Y => cin,
         F => F
      );
   U_3 : ORgate
      PORT MAP (
         X => F,
         Y => dout,
         F => cout
      );
   U_5 : XORgate
      PORT MAP (
         X => cin,
         Y => Y1,
         F => s
      );
   U_6 : XORgate
      PORT MAP (
         X => b,
         Y => a,
         F => Y1
      );

END struct;
