-- hds header_start
--
-- VHDL Architecture ECE290_GATES.ORgate.untitled
--
-- Created:
--          by - mrmcclai.stdt (glsn22.ews.uiuc.edu)
--          at - 18:10:05 06/22/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;


ENTITY ORgate4 IS
   PORT( 
      w : IN     std_logic;
      x : IN     std_logic;
      y : IN     std_logic;
      z : IN     std_logic;
      f : OUT    std_logic
   );

-- Declarations

END ORgate4 ;

-- hds interface_end
ARCHITECTURE untitled OF ORgate4 IS
BEGIN
  F <= W or X or Y or Z after 1 ns;
END untitled;
