-- VHDL Entity LAB3.ripa4bit.symbol
--
-- Created:
--          by - tkim26.ews (gelib-057-21.ews.illinois.edu)
--          at - 08:28:23 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ripa4bit IS
   PORT( 
      a0   : IN     std_logic;
      a1   : IN     std_logic;
      a2   : IN     std_logic;
      a3   : IN     std_logic;
      b0   : IN     std_logic;
      b1   : IN     std_logic;
      b2   : IN     std_logic;
      b3   : IN     std_logic;
      c0   : IN     std_logic;
      c1   : OUT    std_logic;
      c2   : OUT    std_logic;
      c3   : OUT    std_logic;
      cout : OUT    std_logic;
      s0   : OUT    std_logic;
      s1   : OUT    std_logic;
      s2   : OUT    std_logic;
      s3   : OUT    std_logic
   );

-- Declarations

END ripa4bit ;

--
-- VHDL Architecture LAB3.ripa4bit.struct
--
-- Created:
--          by - tkim26.ews (gelib-057-21.ews.illinois.edu)
--          at - 08:28:23 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY LAB3;

ARCHITECTURE struct OF ripa4bit IS

   -- Architecture declarations

   -- Internal signal declarations

   -- Implicit buffer signal declarations
   SIGNAL c3_internal : std_logic;
   SIGNAL c2_internal : std_logic;
   SIGNAL c1_internal : std_logic;


   -- Component Declarations
   COMPONENT full_adder
   PORT (
      a    : IN     std_logic ;
      b    : IN     std_logic ;
      cin  : IN     std_logic ;
      cout : OUT    std_logic ;
      s    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder USE ENTITY LAB3.full_adder;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : full_adder
      PORT MAP (
         a    => a3,
         b    => b3,
         cin  => c3_internal,
         cout => cout,
         s    => s3
      );
   U_1 : full_adder
      PORT MAP (
         a    => a2,
         b    => b2,
         cin  => c2_internal,
         cout => c3_internal,
         s    => s2
      );
   U_2 : full_adder
      PORT MAP (
         a    => a1,
         b    => b1,
         cin  => c1_internal,
         cout => c2_internal,
         s    => s1
      );
   U_3 : full_adder
      PORT MAP (
         a    => a0,
         b    => b0,
         cin  => c0,
         cout => c1_internal,
         s    => s0
      );

   -- Implicit buffered output assignments
   c3 <= c3_internal;
   c2 <= c2_internal;
   c1 <= c1_internal;

END struct;
