-- VHDL Entity LAB3.ripple64.symbol
--
-- Created:
--          by - tkim26.ews (evrt-252-20.ews.illinois.edu)
--          at - 10:17:46 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ripple64 IS
   PORT( 
      A      : IN     std_logic_vector (63 DOWNTO 0);
      B      : IN     std_logic_vector (63 DOWNTO 0);
      Cin    : IN     std_logic;
      Cout63 : OUT    std_logic;
      S      : OUT    std_logic_vector (63 DOWNTO 0)
   );

-- Declarations

END ripple64 ;

--
-- VHDL Architecture LAB3.ripple64.struct
--
-- Created:
--          by - tkim26.ews (evrt-252-20.ews.illinois.edu)
--          at - 10:17:46 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY LAB3;

ARCHITECTURE struct OF ripple64 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Cout  : std_logic;
   SIGNAL Cout1 : std_logic;
   SIGNAL Cout2 : std_logic;
   SIGNAL Cout3 : std_logic;
   SIGNAL Cout4 : std_logic;
   SIGNAL Cout5 : std_logic;
   SIGNAL Cout6 : std_logic;


   -- Component Declarations
   COMPONENT ripple8
   PORT (
      A    : IN     std_logic_vector (7 DOWNTO 0);
      B    : IN     std_logic_vector (7 DOWNTO 0);
      Cin  : IN     std_logic ;
      Cout : OUT    std_logic ;
      S    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ripple8 USE ENTITY LAB3.ripple8;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : ripple8
      PORT MAP (
         A    => A(7 DOWNTO 0),
         B    => B(7 DOWNTO 0),
         Cin  => Cin,
         Cout => Cout6,
         S    => S(7 DOWNTO 0)
      );
   I1 : ripple8
      PORT MAP (
         A    => A(15 DOWNTO 8),
         B    => B(15 DOWNTO 8),
         Cin  => Cout6,
         Cout => Cout5,
         S    => S(15 DOWNTO 8)
      );
   I2 : ripple8
      PORT MAP (
         A    => A(23 DOWNTO 16),
         B    => B(23 DOWNTO 16),
         Cin  => Cout5,
         Cout => Cout4,
         S    => S(23 DOWNTO 16)
      );
   I3 : ripple8
      PORT MAP (
         A    => A(31 DOWNTO 24),
         B    => B(31 DOWNTO 24),
         Cin  => Cout4,
         Cout => Cout3,
         S    => S(31 DOWNTO 24)
      );
   I4 : ripple8
      PORT MAP (
         A    => A(39 DOWNTO 32),
         B    => B(39 DOWNTO 32),
         Cin  => Cout3,
         Cout => Cout2,
         S    => S(39 DOWNTO 32)
      );
   I5 : ripple8
      PORT MAP (
         A    => A(47 DOWNTO 40),
         B    => B(47 DOWNTO 40),
         Cin  => Cout2,
         Cout => Cout1,
         S    => S(47 DOWNTO 40)
      );
   I6 : ripple8
      PORT MAP (
         A    => A(55 DOWNTO 48),
         B    => B(55 DOWNTO 48),
         Cin  => Cout1,
         Cout => Cout,
         S    => S(55 DOWNTO 48)
      );
   I7 : ripple8
      PORT MAP (
         A    => A(63 DOWNTO 56),
         B    => B(63 DOWNTO 56),
         Cin  => Cout,
         Cout => Cout63,
         S    => S(63 DOWNTO 56)
      );

END struct;
