-- VHDL Entity LAB3.ripple8.symbol
--
-- Created:
--          by - tkim26.ews (evrt-252-20.ews.illinois.edu)
--          at - 10:17:46 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ripple8 IS
   PORT( 
      A    : IN     std_logic_vector (7 DOWNTO 0);
      B    : IN     std_logic_vector (7 DOWNTO 0);
      Cin  : IN     std_logic;
      Cout : OUT    std_logic;
      S    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END ripple8 ;

--
-- VHDL Architecture LAB3.ripple8.struct
--
-- Created:
--          by - tkim26.ews (evrt-252-20.ews.illinois.edu)
--          at - 10:17:46 09/21/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY LAB3;

ARCHITECTURE struct OF ripple8 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Cout1 : std_logic;
   SIGNAL Cout2 : std_logic;
   SIGNAL Cout3 : std_logic;
   SIGNAL Cout4 : std_logic;
   SIGNAL Cout5 : std_logic;
   SIGNAL Cout6 : std_logic;
   SIGNAL Cout7 : std_logic;


   -- Component Declarations
   COMPONENT FA
   PORT (
      a    : IN     std_logic ;
      b    : IN     std_logic ;
      cin  : IN     std_logic ;
      cout : OUT    std_logic ;
      s    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FA USE ENTITY LAB3.FA;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : FA
      PORT MAP (
         A    => B(0),
         B    => A(0),
         Cin  => Cin,
         Cout => Cout1,
         S    => S(0)
      );
   I1 : FA
      PORT MAP (
         A    => B(1),
         B    => A(1),
         Cin  => Cout1,
         Cout => Cout2,
         S    => S(1)
      );
   I2 : FA
      PORT MAP (
         A    => B(2),
         B    => A(2),
         Cin  => Cout2,
         Cout => Cout3,
         S    => S(2)
      );
   I3 : FA
      PORT MAP (
         A    => B(3),
         B    => A(3),
         Cin  => Cout3,
         Cout => Cout4,
         S    => S(3)
      );
   I4 : FA
      PORT MAP (
         A    => B(4),
         B    => A(4),
         Cin  => Cout4,
         Cout => Cout5,
         S    => S(4)
      );
   I5 : FA
      PORT MAP (
         A    => B(5),
         B    => A(5),
         Cin  => Cout5,
         Cout => Cout6,
         S    => S(5)
      );
   I6 : FA
      PORT MAP (
         A    => B(6),
         B    => A(6),
         Cin  => Cout6,
         Cout => Cout7,
         S    => S(6)
      );
   I7 : FA
      PORT MAP (
         A    => B(7),
         B    => A(7),
         Cin  => Cout7,
         Cout => Cout,
         S    => S(7)
      );

END struct;
