-- VHDL Entity ece290_project1_lib.scrambler_together.symbol
--
-- Created:
--          by - akim77.ews (evrt-252-37.ews.illinois.edu)
--          at - 21:56:40 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY scrambler_together IS
-- Declarations

END scrambler_together ;

--
-- VHDL Architecture ece290_project1_lib.scrambler_together.struct
--
-- Created:
--          by - akim77.ews (evrt-252-37.ews.illinois.edu)
--          at - 21:56:40 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece290_project1_lib;

ARCHITECTURE struct OF scrambler_together IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL a0  : std_logic;
   SIGNAL a1  : std_logic;
   SIGNAL a10 : std_logic;
   SIGNAL a11 : std_logic;
   SIGNAL a12 : std_logic;
   SIGNAL a13 : std_logic;
   SIGNAL a14 : std_logic;
   SIGNAL a15 : std_logic;
   SIGNAL a16 : std_logic;
   SIGNAL a17 : std_logic;
   SIGNAL a18 : std_logic;
   SIGNAL a19 : std_logic;
   SIGNAL a2  : std_logic;
   SIGNAL a3  : std_logic;
   SIGNAL a4  : std_logic;
   SIGNAL a5  : std_logic;
   SIGNAL a6  : std_logic;
   SIGNAL a7  : std_logic;
   SIGNAL a8  : std_logic;
   SIGNAL a9  : std_logic;
   SIGNAL w   : std_logic;
   SIGNAL w1  : std_logic;
   SIGNAL w2  : std_logic;
   SIGNAL w3  : std_logic;
   SIGNAL w4  : std_logic;
   SIGNAL x   : std_logic;
   SIGNAL x1  : std_logic;
   SIGNAL x2  : std_logic;
   SIGNAL x3  : std_logic;
   SIGNAL x4  : std_logic;
   SIGNAL y   : std_logic;
   SIGNAL y1  : std_logic;
   SIGNAL y2  : std_logic;
   SIGNAL y3  : std_logic;
   SIGNAL y4  : std_logic;
   SIGNAL z   : std_logic;
   SIGNAL z1  : std_logic;
   SIGNAL z2  : std_logic;
   SIGNAL z3  : std_logic;
   SIGNAL z4  : std_logic;


   -- Component Declarations
   COMPONENT scrambler
   PORT (
      w  : IN     std_logic ;
      x  : IN     std_logic ;
      y  : IN     std_logic ;
      z  : IN     std_logic ;
      a0 : OUT    std_logic ;
      a1 : OUT    std_logic ;
      a2 : OUT    std_logic ;
      a3 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : scrambler USE ENTITY ece290_project1_lib.scrambler;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : scrambler
      PORT MAP (
         w  => w,
         x  => x,
         y  => y,
         z  => z,
         a0 => a0,
         a1 => a1,
         a2 => a2,
         a3 => a3
      );
   U_1 : scrambler
      PORT MAP (
         w  => w1,
         x  => x1,
         y  => y1,
         z  => z1,
         a0 => a4,
         a1 => a5,
         a2 => a7,
         a3 => a6
      );
   U_2 : scrambler
      PORT MAP (
         w  => w2,
         x  => x2,
         y  => y2,
         z  => z2,
         a0 => a8,
         a1 => a9,
         a2 => a11,
         a3 => a10
      );
   U_3 : scrambler
      PORT MAP (
         w  => w3,
         x  => x3,
         y  => y3,
         z  => z3,
         a0 => a12,
         a1 => a13,
         a2 => a15,
         a3 => a14
      );
   U_4 : scrambler
      PORT MAP (
         w  => w4,
         x  => x4,
         y  => y4,
         z  => z4,
         a0 => a16,
         a1 => a17,
         a2 => a19,
         a3 => a18
      );

END struct;
