-- VHDL Entity ece290_project1_lib.scrambler2.symbol
--
-- Created:
--          by - akim77.ews (evrt-252-37.ews.illinois.edu)
--          at - 20:05:24 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY scrambler2 IS
-- Declarations

END scrambler2 ;

--
-- VHDL Architecture ece290_project1_lib.scrambler2.struct
--
-- Created:
--          by - akim77.ews (evrt-252-37.ews.illinois.edu)
--          at - 20:05:24 09/26/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF scrambler2 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL a2     : std_logic;
   SIGNAL din0   : std_logic;
   SIGNAL din1   : std_logic;
   SIGNAL din2   : std_logic;
   SIGNAL din3   : std_logic;
   SIGNAL din4   : std_logic;
   SIGNAL din5   : std_logic;
   SIGNAL dout10 : std_logic;
   SIGNAL dout11 : std_logic;
   SIGNAL dout12 : std_logic;
   SIGNAL dout13 : std_logic;
   SIGNAL dout14 : std_logic;
   SIGNAL dout15 : std_logic;
   SIGNAL dout16 : std_logic;
   SIGNAL dout17 : std_logic;
   SIGNAL dout18 : std_logic;
   SIGNAL dout19 : std_logic;
   SIGNAL dout20 : std_logic;
   SIGNAL dout21 : std_logic;
   SIGNAL dout22 : std_logic;
   SIGNAL dout23 : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout6  : std_logic;
   SIGNAL dout7  : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL dout9  : std_logic;
   SIGNAL w      : std_logic;
   SIGNAL wnot   : std_logic;
   SIGNAL x      : std_logic;
   SIGNAL xnot   : std_logic;
   SIGNAL y      : std_logic;
   SIGNAL z      : std_logic;



BEGIN

   -- ModuleWare code(v1.7) for instance 'U_1' of 'and'
   dout16 <= dout5 AND y;

   -- ModuleWare code(v1.7) for instance 'U_2' of 'and'
   dout8 <= wnot AND xnot;

   -- ModuleWare code(v1.7) for instance 'U_4' of 'and'
   dout17 <= z AND dout8;

   -- ModuleWare code(v1.7) for instance 'U_5' of 'and'
   dout12 <= x AND dout11;

   -- ModuleWare code(v1.7) for instance 'U_6' of 'and'
   dout6 <= din0 AND din1;

   -- ModuleWare code(v1.7) for instance 'U_7' of 'and'
   dout19 <= dout10 AND dout12;

   -- ModuleWare code(v1.7) for instance 'U_8' of 'and'
   dout4 <= w AND x;

   -- ModuleWare code(v1.7) for instance 'U_19' of 'and'
   dout10 <= dout9 AND dout7;

   -- ModuleWare code(v1.7) for instance 'U_20' of 'and'
   dout18 <= y AND dout6;

   -- ModuleWare code(v1.7) for instance 'U_21' of 'and'
   dout5 <= w AND x;

   -- ModuleWare code(v1.7) for instance 'U_25' of 'and'
   dout15 <= dout4 AND z;

   -- ModuleWare code(v1.7) for instance 'U_36' of 'and'
   dout13 <= din2 AND din3;

   -- ModuleWare code(v1.7) for instance 'U_37' of 'and'
   dout14 <= din4 AND w;

   -- ModuleWare code(v1.7) for instance 'U_38' of 'and'
   dout20 <= dout13 AND dout14;

   -- ModuleWare code(v1.7) for instance 'U_26' of 'inv'
   wnot <= NOT(w);

   -- ModuleWare code(v1.7) for instance 'U_27' of 'inv'
   xnot <= NOT(x);

   -- ModuleWare code(v1.7) for instance 'U_28' of 'inv'
   dout7 <= NOT(y);

   -- ModuleWare code(v1.7) for instance 'U_29' of 'inv'
   dout9 <= NOT(w);

   -- ModuleWare code(v1.7) for instance 'U_30' of 'inv'
   din0 <= NOT(w);

   -- ModuleWare code(v1.7) for instance 'U_31' of 'inv'
   dout11 <= NOT(z);

   -- ModuleWare code(v1.7) for instance 'U_32' of 'inv'
   din1 <= NOT(x);

   -- ModuleWare code(v1.7) for instance 'U_33' of 'inv'
   din2 <= NOT(x);

   -- ModuleWare code(v1.7) for instance 'U_34' of 'inv'
   din3 <= NOT(y);

   -- ModuleWare code(v1.7) for instance 'U_35' of 'inv'
   din4 <= NOT(z);

   -- ModuleWare code(v1.7) for instance 'U_12' of 'or'
   a2 <= dout23 OR dout22;

   -- ModuleWare code(v1.7) for instance 'U_14' of 'or'
   din5 <= dout17 OR dout18;

   -- ModuleWare code(v1.7) for instance 'U_15' of 'or'
   dout21 <= dout15 OR dout16;

   -- ModuleWare code(v1.7) for instance 'U_16' of 'or'
   dout23 <= dout21 OR din5;

   -- ModuleWare code(v1.7) for instance 'U_17' of 'or'
   dout22 <= dout19 OR dout20;

   -- Instance port mappings.

END struct;
