-- VHDL Entity project1_lib.transmitter.symbol
--
-- Created:
--          by - kim705.ews (evrt-252-23.ews.illinois.edu)
--          at - 22:33:03 10/01/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY transmitter IS
   PORT( 
      a     : IN     std_logic;
      b     : IN     std_logic;
      c     : IN     std_logic;
      d     : IN     std_logic;
      x0    : IN     std_logic;
      x1    : IN     std_logic;
      x2    : IN     std_logic;
      x3    : IN     std_logic;
      x4    : IN     std_logic;
      dbus0 : OUT    std_logic_vector (19 DOWNTO 0)
   );

-- Declarations

END transmitter ;

--
-- VHDL Architecture project1_lib.transmitter.struct
--
-- Created:
--          by - kim705.ews (evrt-252-23.ews.illinois.edu)
--          at - 22:33:03 10/01/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF transmitter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL x0a  : std_logic;
   SIGNAL x0a1 : std_logic;
   SIGNAL x0a2 : std_logic;
   SIGNAL x0a3 : std_logic;
   SIGNAL x0a4 : std_logic;
   SIGNAL x0b  : std_logic;
   SIGNAL x0b1 : std_logic;
   SIGNAL x0b2 : std_logic;
   SIGNAL x0b3 : std_logic;
   SIGNAL x0b4 : std_logic;
   SIGNAL x0c  : std_logic;
   SIGNAL x0c1 : std_logic;
   SIGNAL x0c2 : std_logic;
   SIGNAL x0c3 : std_logic;
   SIGNAL x0c4 : std_logic;
   SIGNAL x0d  : std_logic;
   SIGNAL x0d1 : std_logic;
   SIGNAL x0d2 : std_logic;
   SIGNAL x0d3 : std_logic;
   SIGNAL x0d4 : std_logic;


   -- Component Declarations
   COMPONENT encryption
   PORT (
      a   : IN     std_logic ;
      b   : IN     std_logic ;
      c   : IN     std_logic ;
      d   : IN     std_logic ;
      x0  : IN     std_logic ;
      x0a : OUT    std_logic ;
      x0b : OUT    std_logic ;
      x0c : OUT    std_logic ;
      x0d : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT scrambler
   PORT (
      w  : IN     std_logic ;
      x  : IN     std_logic ;
      y  : IN     std_logic ;
      z  : IN     std_logic ;
      a0 : OUT    std_logic ;
      a1 : OUT    std_logic ;
      a2 : OUT    std_logic ;
      a3 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : encryption USE ENTITY project1_lib.encryption;
   FOR ALL : scrambler USE ENTITY project1_lib.scrambler;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x0,
         x0a => x0a,
         x0b => x0b,
         x0c => x0c,
         x0d => x0d
      );
   U_2 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x1,
         x0a => x0a1,
         x0b => x0b1,
         x0c => x0c1,
         x0d => x0d1
      );
   U_4 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x2,
         x0a => x0a2,
         x0b => x0b2,
         x0c => x0c2,
         x0d => x0d2
      );
   U_6 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x3,
         x0a => x0a3,
         x0b => x0b3,
         x0c => x0c3,
         x0d => x0d3
      );
   U_8 : encryption
      PORT MAP (
         a   => a,
         b   => b,
         c   => c,
         d   => d,
         x0  => x4,
         x0a => x0a4,
         x0b => x0b4,
         x0c => x0c4,
         x0d => x0d4
      );
   U_1 : scrambler
      PORT MAP (
         w  => x0a,
         x  => x0b,
         y  => x0d,
         z  => x0c,
         a0 => dbus0(0),
         a1 => dbus0(1),
         a2 => dbus0(3),
         a3 => dbus0(2)
      );
   U_3 : scrambler
      PORT MAP (
         w  => x0a1,
         x  => x0b1,
         y  => x0d1,
         z  => x0c1,
         a0 => dbus0(4),
         a1 => dbus0(5),
         a2 => dbus0(7),
         a3 => dbus0(6)
      );
   U_5 : scrambler
      PORT MAP (
         w  => x0a2,
         x  => x0b2,
         y  => x0d2,
         z  => x0c2,
         a0 => dbus0(8),
         a1 => dbus0(9),
         a2 => dbus0(11),
         a3 => dbus0(10)
      );
   U_7 : scrambler
      PORT MAP (
         w  => x0a3,
         x  => x0b3,
         y  => x0d3,
         z  => x0c3,
         a0 => dbus0(12),
         a1 => dbus0(13),
         a2 => dbus0(15),
         a3 => dbus0(14)
      );
   U_9 : scrambler
      PORT MAP (
         w  => x0a4,
         x  => x0b4,
         y  => x0d4,
         z  => x0c4,
         a0 => dbus0(16),
         a1 => dbus0(17),
         a2 => dbus0(19),
         a3 => dbus0(18)
      );

END struct;
